README.rst, scripts/unacceptedTermsAndConditions/README.rst, scripts/unacceptedTermsAndConditions/script.sh, scripts/unacceptedTermsAndConditions/trims.awk
@chemaper @jicarretero
- Including scripts to delete users that does not accept the new Terms & Conditions.
- Changing in README file in order to reflect this change.
=> Integrate delete unaccepted term and condition

analyse_report_data.py, openstackmap.py, user_resources.py, utils/rotated_files.py
@flopezag
improve logging (add cause of exception)
add tool to unify reports and extract informations, as users that failed
update openstackmap. Now it is a class with improved functionality
Locally
[editar]
=> improve diagnosis

.bumpversion.cfg, sonar-project.properties
@chemaper , @jframos 
- Configure sonar project properties.
Tests in the Jenkins environment.
=> fix: dev:Configuring Sonar to show code quality

requirements_dev.txt
@jframos 
- fixing requirement for tests
=> fixing requirement for tests

phase0c_change_category.py, phase1_generate_trust_ids.py, phase2_stopvms.py, phase2c_deletespecialports.py, phase3_delete.py, scripts/analyse_report_data.py, skuld/check_users.py, skuld/cinder_resources.py, skuld/impersonate.py, skuld/user_resources.py, utils/log.py, utils/osclients.py
@flopezag 
Fixes some problems discovered doing the task CLAUDIA-5721 (cleaning resources in two regions different than Spain2)
Locally
=> Fix/multiregion (CLAUDIA-5721)

utils/osclients.py
@flopezag @jframos 
This is only to synchronise a problem detected in osclients.py while I was working in CLAUDIA-5035 in Glancesync. The file is the same than in Glancesync.
Locally
=> fix a problem with APIv2 detected implementing 5035 in glancesync

tests/acceptance/features/keystone.feature
@jframos 
- Correction of Jenkins CI problem in acceptance tests
- Minor change in description of feature.
Locally and in Jenkins (CLI and Web Interface)
=> Minor change in description of feature and correction of CI

.travis.yml, README.rst
@chemaper @jframos 
Add coveralls configuration to the repo.
Tested the execution in Travis and sent data to Coveralls (https://coveralls.io/builds/4419934) in the current branch.
=> Adding coveralls to the repository

tests/units/test_impersonate.py
@flopezag
unit tests for class TrustFactory, used to impersonate users using trust-id
Locally
=> claudia-5784

scripts/classify_resources_by_owners.py, tests/units/test_classify_resources_by_owner.py
@flopezag
Code to differentiate what trial/community users has access to the region.
This information is also used to detect resources owned by projects that are community/trial, but in  a region where are not authorised.
Finally, a unit test for all the methods of the script, not only the new functionality, has been written.
Locally
=> Claudia 5833

tests/units/test_novaresources.py
@flopezag
Unit tests for nova-resources
Locally
=> claudia-5777

scripts/classify_resources_by_owners.py, tests/units/test_classify_resources_by_owner.py
@flopezag
Fix a wrong change introduced in claudia-5833
Locally
=> fix a bug introduced in last pull request @minor

.travis.yml, scripts/userListPerRegion/README.rst, scripts/userListPerRegion/__init__.py, scripts/userListPerRegion/requirements.txt, scripts/userListPerRegion/users.py, test-requirements.txt, tests/units/tests_user_per_region_script.py
@chemaper 
Adding script to recover all the users with their email from a specific Region.
Locally.
=> Create script to recover all the user from one region

requirements.txt
@geonexus 
Resolve the CI problems in the execution of the tests
Locally
=> Adding library to the requirements file

.gitignore, scripts/classify_resources_by_owners.py, scripts/userListPerRegion/users.py, skuld/change_password.py, skuld/openstackmap.py, tests/install_testbed/change_idm_password.py, tests/install_testbed/generate_region_config.py, tests/install_testbed/launch_vm.py, tests/install_testbed/register_region.py, tests/units/test_impersonate.py, tests/units/test_openstackmap.py, tests/units/test_osclients.py, tests/units/tests_user_per_region_script.py, utils/osclients.py
@jicarretero 
- Adding the obtention of user list from osclients
- Joining the result with the one obtained from the Keystone - IdM
- Produce the result
Locally
=> Making a second analisis of the user data

tests/acceptance/features/environment.py, tests/acceptance/features/steps/keystone_token.py
=> fix imports

tests/install_testbed/change_idm_password.py, tests/install_testbed/keystone_work.sh, tests/install_testbed/launch_vm.py
@pratid
Remove Spain2 hardcoded and  bad import
It is a deployment script used in cloud-init. To be testbed when merged
=> Remove Spain2 hardcoded and  bad import

tests/install_testbed/register_region.py
#REVIEWERS
@jesuspg 
#DESCRIPTION
It updates the way to check if the endpoint exists and create them (taking into account different regions)
#Test
To be testbed
=> update region update

tests/install_testbed/change_idm_password.py, tests/install_testbed/deploytwotestbeds.py, tests/install_testbed/launch_vm.py
@jesuspg 
Check that keystone has been deployed
locally
=> wait for keystone started

docker/Dockerfile, docker/docker-compose.yml, docker/log_rules, docker/settings.py, docker/start.sh
@jesuspg 
Adding configuration in conf/setttings.py
LOCALLY
=> Adding configuration in conf/setttings.py

docker/Dockerfile_build, docker/threeglances/Dockerfile, docker/threeglances/docker-compose.yml, docker/threeglances/start.sh, tests/install_testbed/cloudconfig_only_glance, tests/install_testbed/deploythreeglances.py, tests/install_testbed/install_only_glance.sh, tests/install_testbed/launch_vm.py, tests/install_testbed/settings.py
@jesuspg 
Adding docker for build and pass unit tests
###TEST
Done
=> Creating docker file for build tests

docker/onetestbed/start.sh, docker/threeglances/start.sh, docker/twotestbed/start.sh, tests/install_testbed/change_idm_password.py, tests/install_testbed/cloudconfig_phone_home, tests/install_testbed/deploythreeglances.py, tests/install_testbed/deploytwotestbeds.py, tests/install_testbed/generate_region_config.py, tests/install_testbed/launch_vm.py, tests/install_testbed/launch_vm_phonehome.py, tests/install_testbed/register_region.py, tests/install_testbed/settings.py, tests/units/test_expired_users.py
@jesuspg 
Change for updating domain default in the testbed. Update all the environment variables.
Locally for parts. It is needed to be merged to develop to be able to be testbed from cloud-init
=> Update for creating real testbed

fiwareskuld/user_resources.py, fiwareskuld/utils/osclients.py, fiwareskuld/utils/rotated_files.py, tests/units/test_rotated_files.py
@jesuspg @hmunfru 
- Add try-except in the creation of the BlueprintResources class.
- Control of the UserResources class to the blueprints value.
- Coding style.
Locally with the OpenStack docker testbed deploy in my FIWARE Lab account (without PaaS entry point).
=> Resolve not service entrypoint for PaaS Manager
